// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"context"
)

type Querier interface {
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Categories, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (Users, error)
	DeleteCategory(ctx context.Context, id int32) error
	GetCategories(ctx context.Context, arg GetCategoriesParams) ([]Categories, error)
	GetCategory(ctx context.Context, id int32) (Categories, error)
	GetUser(ctx context.Context, username string) (Users, error)
	GetUserById(ctx context.Context, id int32) (Users, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Categories, error)
}

var _ Querier = (*Queries)(nil)
